version: '3.0'

expectations:
  population_size: 500

actions:

  generate_measure_cohort_1:
    # week 45 2020 to 20 2020 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measure --index-date-range "2020-11-02 to 2021-01-03 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_measure_cohort_2:
    # week 51 2020 to 03 2021 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measure --index-date-range "2021-01-04 to 2021-03-07 by week"
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measure
    needs: [generate_measure_cohort_1, generate_measure_cohort_2]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  standardise_and_plot:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        tables: output/*_rate.csv
        graph: output/time_series_plot.svg

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_cohort
    outputs:
      highly_sensitive:
        cohort: output/input_cohort.csv

  count_by_strata:
    run: python:latest python analysis/all_time_counts.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        tables: output/counts_table.csv
        practice_summ: output/practice_summ.csv

