version: '3.0'

expectations:
  population_size: 2000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_cohort --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_cohort.feather

  count_by_strata:
    run: python:latest python analysis/all_time_counts.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        table: output/counts_table.csv
        practice_distribution: output/practice_distribution.csv
        per_week: output/code_use_per_week_long_covid.csv
        per_week_pvf: output/code_use_per_week_post_viral_fatigue.csv
        code_table: output/all_long_covid_codes.csv
        practice_summ: output/practice_summ.txt
