name: Test that the project is runnable

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_model:
    runs-on: ubuntu-latest
    name: Test the project can run, using dummy data
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opensafely-cohort-extractor
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        # It seems we can't do this with the standard GITHUB_TOKEN, but
        # have to use a personal token with the correct permissions instead
        login-server: docker.opensafely.org
        username: docker
        password: ${{ secrets.OPENSAFELY_DOCKER_PASSWORD }}

    - name: Update codelists
      run: cohortextractor update_codelists
    - name: Check codelists are up to date
      run: '[[ -z $(git status --porcelain codelists) ]] || (echo "Uncommitted changes to codelists detected, aborting" && exit 1)'

    - name: Run the project
      run: cohortextractor --verbose run dummy run_all expectations
