name: Test that the project is runnable

on: [push, workflow_dispatch]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_RO_TOKEN: ${{ secrets.DOCKER_RO_TOKEN }}
  STATA_LICENSE: ${{ secrets.STATA_LICENSE }}
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the project can run, using dummy data
    steps:
    - name: Test that the project is runnable
      uses: opensafely-core/research-action@v1
